import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { db, pool } from "./client.js";
import { categories, products } from "./schema.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Bootstrap data for an empty database, taken from the frontend's fallback
// menu so the content is not duplicated into a second file.
//
// Insert-only, deliberately. This used to upsert, which meant re-running it
// silently reset every price edit and the whole custom ordering back to
// whatever the JSON last said. PostgreSQL is the source of truth now; the JSON
// flows the other way, via `npm run db:export-menu`.
const MENU_DATA_PATH = path.resolve(
  __dirname,
  "../../../frontend/src/constants/menuData.json",
);

interface MenuJsonItem {
  id: string;
  name: { tr: string; en: string };
  price: number;
  description: { tr: string; en: string };
  image: string;
  /** Present once the JSON has been regenerated by `db:export-menu`. */
  isAvailable?: boolean;
}

interface MenuJsonCategory {
  id: string;
  name: { tr: string; en: string };
  items: MenuJsonItem[];
}

interface MenuJson {
  categories: MenuJsonCategory[];
}

async function seed() {
  const raw = await readFile(MENU_DATA_PATH, "utf-8");
  const menu: MenuJson = JSON.parse(raw);

  const categoryRows = menu.categories.map((category, index) => ({
    slug: category.id,
    nameTr: category.name.tr,
    nameEn: category.name.en,
    sortOrder: index,
  }));

  const insertedCategories = await db
    .insert(categories)
    .values(categoryRows)
    .onConflictDoNothing({ target: categories.slug })
    .returning({ id: categories.id, slug: categories.slug });

  // onConflictDoNothing returns only the rows it actually inserted, so on a
  // re-run this map would be empty and every product would get a null
  // categoryId. Read the ids back instead of trusting the insert's output.
  const allCategories = await db
    .select({ id: categories.id, slug: categories.slug })
    .from(categories);
  const categoryIdBySlug = new Map(allCategories.map((c) => [c.slug, c.id]));

  const productRows = menu.categories.flatMap((category) =>
    category.items.map((item, index) => ({
      slug: item.id,
      categoryId: categoryIdBySlug.get(category.id)!,
      nameTr: item.name.tr,
      nameEn: item.name.en,
      descriptionTr: item.description.tr,
      descriptionEn: item.description.en,
      price: item.price.toFixed(2),
      imagePath: item.image,
      sortOrder: index,
      isAvailable: item.isAvailable ?? true,
    })),
  );

  const insertedProducts = await db
    .insert(products)
    .values(productRows)
    .onConflictDoNothing({ target: products.slug })
    .returning({ id: products.id, slug: products.slug });

  console.log(
    `Seeded ${insertedCategories.length} new categories and ${insertedProducts.length} new products from ${MENU_DATA_PATH}. ` +
      "Existing rows were left untouched.",
  );
}

seed()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await pool.end();
  });
